name: Quester
version: ${yml.version}
description: Quester provides ability to create highly customizable quests directly in game.
author: raGan
website: http://dev.bukkit.org/server-mods/quester/
main: com.gmail.molnardad.quester.Quester
softdepend: [Vault, Citizens, Denizen]
commands:
    q:
        description: Main (and only) quester command.
        aliases: [quest, quester]
permissions:
    quester.admin:
        children:
            quester.modify: true
            quester.use: true
        default: op
    quester.modify:
        default: op
    quester.use:
        children:
            quester.use.help: true
            quester.use.start: true
            quester.use.npc: true
            quester.use.sign: true
            quester.use.list: true
            quester.use.show: true
            quester.use.profile: true
            quester.use.done: true
            quester.use.cancel: true
            quester.use.progress: true
            quester.use.quests: true
            quester.use.switch: true
        default: true
    quester.use.start:
        children:
            quester.use.start.pick: true
            quester.use.start.random: true
